services:
  - type: worker
    name: keng-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
